import { ProjectT } from '@/common/types/projects';
import { v4 } from 'uuid';

export class ProjectsUiFct {
  public static readonly data: ProjectT[] = [
    {
      title: 'Invoices App',
      repo: 'https://github.com/AlexanderMatveev2908/InvoicesApp',
      live: 'https://invoices-app-client.fly.dev/',
      appType: 'full-stack',
      defName: 'invoices',
      down: true,
    },
    {
      title: 'Recipes App',
      repo: 'https://github.com/AlexanderMatveev2908/RecipesApp',
      live: 'https://recipes-app-client.fly.dev/',
      appType: 'full-stack',
      defName: 'recipes',
      down: false,
    },
    {
      title: 'Product Feedbacks',
      repo: 'https://github.com/AlexanderMatveev2908/asp-product-feedback',
      live: 'https://asp-product-feedback-client.fly.dev/',
      appType: 'full-stack',
      defName: 'feedbacks',
      down: true,
    },
    {
      title: 'ASP Weather App',
      repo: 'https://github.com/AlexanderMatveev2908/asp-weather-app',
      live: 'https://asp-weather-app-client.fly.dev/',
      appType: 'full-stack',
      defName: 'weather',
      down: true,
    },
    {
      title: 'ASP Job Application Tracker',
      repo: 'https://github.com/AlexanderMatveev2908/asp-job-application-tracker',
      live: 'https://asp-job-application-tracker-client.fly.dev/',
      appType: 'full-stack',
      defName: 'jobs_ng_java',
      down: true,
    },
    {
      title: 'PSN Job Application Tracker',
      repo: 'https://github.com/AlexanderMatveev2908/psn-job-application-tracker',
      live: 'https://psn-job-application-tracker-client.fly.dev/',
      appType: 'full-stack',
      defName: 'jobs_java',
      down: true,
    },
    {
      title: 'PFN Job Application Tracker',
      repo: 'https://github.com/AlexanderMatveev2908/PFN-job-application-tracker',
      live: 'https://pfn-job-application-tracker-client.fly.dev/',
      appType: 'full-stack',
      defName: 'jobs',
      down: true,
    },
    {
      title: 'Qr-Code Generator',
      repo: 'https://github.com/AlexanderMatveev2908/next-qr-code-generator',
      live: 'https://next-qr-code-generator-client.fly.dev/',
      appType: 'full-stack',
      defName: 'qr_code',
      down: true,
    },
    {
      title: 'Courses App',
      repo: 'https://github.com/AlexanderMatveev2908/next-pern-courses',
      live: 'https://next-pern-courses-client.fly.dev/',
      appType: 'full-stack',
      defName: 'courses',
      down: true,
    },
    {
      title: 'Memory Game',
      repo: 'https://github.com/AlexanderMatveev2908/next-memory-game',
      live: 'https://next-memory-game-ten.vercel.app/',
      appType: 'frontend',
      defName: 'memory',
      down: false,
    },
    {
      title: 'Bookstore App',
      repo: 'https://github.com/AlexanderMatveev2908/pern__book',
      live: 'https://pern-book.fly.dev/',
      appType: 'full-stack',
      defName: 'pern_book',
      down: true,
    },
    {
      title: 'Food Delivery App',
      repo: 'https://github.com/AlexanderMatveev2908/MERN__EAT',
      live: 'https://food-app-aqkc.onrender.com/',
      appType: 'full-stack',
      defName: 'mern_eat',
      down: true,
    },
    {
      title: 'Tic Tac Toe',
      repo: 'https://github.com/AlexanderMatveev2908/REACT__X0',
      live: 'https://react-x0.onrender.com/',
      appType: 'frontend',
      defName: 'x_o',
      down: false,
    },
    {
      title: 'Hotel Booking App',
      repo: 'https://github.com/AlexanderMatveev2908/MERN__BOOKING',
      live: 'https://mern-booking-app-0w8v.onrender.com/',
      appType: 'full-stack',
      defName: 'mern_book',
      down: true,
    },
    {
      title: 'Calculator IOS',
      repo: 'https://github.com/AlexanderMatveev2908/REACT_CALCULATOR',
      live: 'https://react-calculator-imc7.onrender.com/',
      appType: 'frontend',
      defName: 'calc',
      down: false,
    },
  ].map((el) => ({
    ...el,
    img: `/images/apps/${el.defName}.png`,
    id: v4(),
  })) as ProjectT[];
}
